---
title: "My English activity log"
---

# Books
### Cries Unheard

 This book tells the story of Mary Bell, who whas convicted of manslaughter at age 11 after the murder of two children. The author Gitta Sereny was an Austrian-British biographer, historian, and investigative journalist. She interviewed and profiled infamous figures like Mary Bell.

# Magazines
### The Scientist Magazine
### Science News

# Films

### Lucy
Lucy is a French science fiction action film written and directed by Luc Besson and produced by his wife Virginie Besson. The film stars Scarlett Johansson who plays a woman who gains psychokinetic abilities when a nootropic drug is absorbed into her bloodstream.

# TV series

### Mind Hunter 
Mindhunter is an American crime thriller television series created by Joe Penhall
It's based on the true-crime book Mindhunter: Inside the FBI's Elite Serial Crime Unit 

### Black Mirror

Black Mirror is a British science fiction anthology television series created by Charlie Brooker. 
It's about modern society, it gives an unanticipated consequences of new technologies. Episodes are not related, usually set in an alternative present or the near future.

# Podcasts
### /


